version: 2

aliases:
  - &setup_miniconda
    name: setup_miniconda
    command: |
       mkdir -p workspace
       git clone -b validateNightly git@github.com:CDAT/cdat workspace/cdat
       # install_miniconda.py installs miniconda3 under $WORKDIR/miniconda
       python workspace/cdat/scripts/install_miniconda.py -w $WORKDIR -p 'py3'

  - &conda_rerender
    name: conda_rerender
    command: |
       git clone -b sync_recipe https://github.com/CDAT/conda-recipes.git $WORKDIR/conda-recipes 
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base
       BUILD_SCRIPT="$WORKDIR/conda-recipes/build_tools/conda_build.py"
       python $BUILD_SCRIPT -w $WORKDIR -l $LAST_STABLE -B 0 -p $PKG_NAME -b $CIRCLE_BRANCH --do_rerender
       echo "ls -l $WORKDIR/cdtime-feedstock/.ci_support"
       ls -l $WORKDIR/cdtime-feedstock/.ci_support

  - &conda_build
    name: conda_build
    command: |
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base
       conda config --add channels conda-forge --force
       conda config --set channel_priority strict
       BUILD_SCRIPT="$WORKDIR/conda-recipes/build_tools/conda_build.py"
       python $BUILD_SCRIPT -w $WORKDIR -p $PKG_NAME --build_version $BUILD_VARIANT_VER --do_build

  - &setup_run_tests
    name: setup_run_tests
    environment:
       PKGS: "numpy cdat_info libcdms libdrs_f testsrunner 'libnetcdf=4.6.2'"
       CHANNELS: "-c cdat/label/linatest -c cdat/label/nightly -c conda-forge"
    command: |
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base
       conda create -y -n $ENV_NAME --use-local $CHANNELS "$CONDA_PY_VER" $PKG_NAME $PKGS
       conda activate $ENV_NAME
       conda list

  - &run_tests
    name: run_tests
    command: |
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate $ENV_NAME
       python -c "import $PKG_NAME; import sys; print(sys.path)"
       python run_tests.py -H -v2 -n 2

  - &conda_upload
    name: conda_upload
    command: |
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base
       UPLOAD_OPTIONS="-t $CONDA_UPLOAD_TOKEN upload -u $USER -l $LABEL"
       anaconda $UPLOAD_OPTIONS linux_build/miniconda/conda-bld/linux-64/$PKG_NAME*tar.bz2 --force
       anaconda $UPLOAD_OPTIONS macos_build/miniconda/conda-bld/osx-64/$PKG_NAME*tar.bz2 --force

jobs:
   macos_setup:
      macos:
         xcode: "11.1.0"
      environment:
         WORKDIR: /Users/distiller/project/macos_build
         PKG_NAME: "cdtime"
         LAST_STABLE: "3.1.2"
      steps:
         - run: *setup_miniconda
         - run: *conda_rerender
         - persist_to_workspace:
              root: .
              paths: 
                 - macos_build

   linux_setup:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: /home/circleci/project/linux_build
         PKG_NAME: "cdtime"
         LAST_STABLE: "3.1.2"
      steps:
         - attach_workspace:
              at: .
         - run: *setup_miniconda
         - run: *conda_rerender
         - persist_to_workspace:
              root: .
              paths:
                 - linux_build

   macos_cdtime_py2:
      macos:
         xcode: "11.1.0"
      environment:
         WORKDIR: /Users/distiller/project/macos_build
         PKG_NAME: "cdtime"
         ENV_NAME: "test_cdtime"
         LAST_STABLE: "3.1.2"
         CONDA_PY_VER: "python<3"
         BUILD_VARIANT_VER: "2.7"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build
         - run: *setup_run_tests
         - run: *run_tests
         - store_artifacts:
              path: tests_html
              destination: tests_html
         - store_artifacts:
             path: tests_png
             destination: tests_png
         - persist_to_workspace:
              root: .
              paths:
                 - macos_build/miniconda/conda-bld/osx-64/cdtime*tar.bz2

   macos_cdtime_py37:
      macos:
         xcode: "11.1.0"
      environment:
         WORKDIR: /Users/distiller/project/macos_build
         PKG_NAME: "cdtime"
         ENV_NAME: "test_cdtime"
         LAST_STABLE: "3.1.2"
         CONDA_PY_VER: "python>=3.7,<3.8"
         BUILD_VARIANT_VER: "3.7"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build
         - run: *setup_run_tests
         - run: *run_tests
         - store_artifacts:
              path: tests_html
              destination: tests_html
         - store_artifacts:
             path: tests_png
             destination: tests_png
         - persist_to_workspace:
              root: .
              paths:
                 - macos_build/miniconda/conda-bld/osx-64/cdtime*tar.bz2


   linux_cdtime_py2:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: /home/circleci/project/linux_build
         PKG_NAME: "cdtime"
         ENV_NAME: "test_cdtime"
         LAST_STABLE: "3.1.2"
         CONDA_PY_VER: "python<3"
         BUILD_VARIANT_VER: "2.7"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build
         - run: *setup_run_tests
         - run: *run_tests
         - store_artifacts:
              path: tests_html
              destination: tests_html
         - store_artifacts:
             path: tests_png
             destination: tests_png
         - persist_to_workspace:
              root: .
              paths:
                 - linux_build/miniconda/conda-bld/linux-64/cdtime*tar.bz2

   linux_cdtime_py37:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: /home/circleci/project/linux_build
         PKG_NAME: "cdtime"
         ENV_NAME: "test_cdtime"
         LAST_STABLE: "3.1.2"
         CONDA_PY_VER: "python>=3.7,<3.8"
         BUILD_VARIANT_VER: "3.7"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build
         - run: *setup_run_tests
         - run: *run_tests
         - store_artifacts:
              path: tests_html
              destination: tests_html
         - store_artifacts:
             path: tests_png
             destination: tests_png
         - persist_to_workspace:
              root: .
              paths:
                 - linux_build/miniconda/conda-bld/linux-64/cdtime*tar.bz2

   upload:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: /home/circleci/project/linux_build
         PKG_NAME: "cdtime"
         USER: "cdat"
         LABEL: "linatest"
      steps:
         - attach_workspace:
              at: .
         - run: pwd
         - run: *conda_upload

workflows:
   version: 2
   cdtime:
      jobs:
         - macos_setup
         - linux_setup
         - macos_cdtime_py2:
              requires:
                 - macos_setup
         - macos_cdtime_py37:
              requires:
                 - macos_setup
         - linux_cdtime_py2:
              requires:
                 - linux_setup
         - linux_cdtime_py37:
              requires:
                 - linux_setup
         - upload:
              requires:
                 - macos_cdtime_py2
                 - linux_cdtime_py2
                 - macos_cdtime_py37
                 - linux_cdtime_py37
