version: 2

aliases:
  - &setup_miniconda
    name: setup_miniconda
    command: |
       mkdir -p workspace
       git clone -b validateNightly git@github.com:CDAT/cdat workspace/cdat
       # install_miniconda.py installs miniconda3 under $WORKDIR/miniconda
       python workspace/cdat/scripts/install_miniconda.py -w $WORKDIR -p 'py3'

  - &build_cdtime
    name: build_cdtime
    command: |
       git clone -b sync_recipe https://github.com/CDAT/conda-recipes.git $WORKDIR/conda-recipes 
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base
       python $WORKDIR/conda-recipes/build_tools/conda_build_upload.py -w $WORKDIR -l $LAST_STABLE -B 0 -p cdtime -b $CIRCLE_BRANCH

  - &setup_run_tests
    name: setup_run_tests
    environment:
       PKGS: "numpy cdat_info libcdms libdrs_f testsrunner 'libnetcdf=4.6.2' cdtime"
       CHANNELS: "-c cdat/label/nightly -c conda-forge"
    command: |
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base
       # REVISIT python version
       conda create -y -n test_cdtime --use-local $CHANNELS "$PY_VER" $PKGS
       conda activate test_cdtime
       conda list
       echo "python -c 'import cdtime'"
       python -c "import cdtime"

  - &run_tests
    name: run_tests
    command: |
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       # conda activate base
       conda activate test_cdtime
       echo "python -c 'import cdtime'"
       python -c "import cdtime"
       python -c "import sys; print(sys.path)"
       python run_tests.py -H -v2 -n 2

jobs:
   macos_cdtime_py2:
      macos:
         xcode: "11.1.0"
      environment:
         WORKDIR: "/Users/distiller/project/workdir"
         LAST_STABLE: "3.1.2"
         PY_VER: "python<3"
      steps:
         - checkout
         - run: *setup_miniconda
         - run: *build_cdtime
         - run: *setup_run_tests
         - run: *run_tests

   macos_cdtime_py37:
      macos:
         xcode: "11.1.0"
      environment:
         WORKDIR: "/Users/distiller/project/workdir"
         LAST_STABLE: "3.1.2"
         PY_VER: "python>=3.7,<3.8"
      steps:
         - checkout
         - run: *setup_miniconda
         - run: *build_cdtime
         - run: *setup_run_tests
         - run: *run_tests

   linux_cdtime_py2:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: "/home/circleci/project/workdir"
         LAST_STABLE: "3.1.2"
         PY_VER: "python<3"
      steps:
         - checkout
         - run: *setup_miniconda
         - run: *build_cdtime
         - run: *setup_run_tests
         - run: *run_tests

   linux_cdtime_py37:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: "/home/circleci/project/workdir"
         LAST_STABLE: "3.1.2"
         PY_VER: "python>=3.7,<3.8"
      steps:
         - checkout
         - run: *setup_miniconda
         - run: *build_cdtime
         - run: *setup_run_tests
         - run: *run_tests

workflows:
   version: 2
   cdtime:
      jobs:
         - macos_cdtime_py2
         - macos_cdtime_py37
         - linux_cdtime_py2
         - linux_cdtime_py37

